use crate::state::{SharedState, StateError};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use tracing::{debug, info, trace, warn};

/// Represents an update event generated by command processing.
#[derive(Debug, Clone)]
pub struct RoomUpdate {
    pub room_id: u64,
    pub container: String,
    pub key: String,
    pub value: Option<Value>,
    pub room_counter: u64,
}

const MAX_COMMAND_CONTAINER_LEN: usize = 256;
const MAX_COMMAND_KEY_LEN: usize = 256;
const MAX_LABEL_LEN: usize = 256;

fn validate_container_name(name: &str) -> Result<(), String> {
    if name.len() > MAX_COMMAND_CONTAINER_LEN {
        return Err("ERROR container_name_too_long".into());
    }
    Ok(())
}

fn validate_key_name(key: &str) -> Result<(), String> {
    if key.len() > MAX_COMMAND_KEY_LEN {
        return Err("ERROR key_too_long".into());
    }
    Ok(())
}

fn validate_label_name(label: &str) -> Result<(), String> {
    if label.trim().is_empty() {
        return Err("ERROR label_invalid".into());
    }
    if label.len() > MAX_LABEL_LEN {
        return Err("ERROR label_invalid".into());
    }
    Ok(())
}

/// Process an incoming text command and return a response plus optional room updates.
pub async fn process_command(line: &str, state: &SharedState) -> (String, Vec<RoomUpdate>) {
    let mut remainder = line.trim_start();
    trace!(line = %line, "process_command");

    let (cmd, rest) = match take_token(remainder) {
        Ok((token, rest)) => (token, rest),
        Err(e) => return (e, vec![]),
    };
    remainder = rest;

    match cmd.as_ref() {
        "ROOM.CREATE" => {
            if !remainder.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let mut app = state.write().await;
            let room_id = app.create_room();
            info!(room_id = room_id, "ROOM.CREATE");
            (format!("OK {}", room_id), vec![])
        }
        "ROOM.DELETE" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let mut app = state.write().await;
            match app.delete_room(room_id) {
                Ok(()) => {
                    info!(room_id = room_id, "ROOM.DELETE");
                    ("OK".into(), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "ROOM.LIST" => {
            if !remainder.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let app = state.read().await;
            let rooms = app.list_rooms();
            let payload = serde_json::to_string(&rooms).unwrap_or_else(|_| "[]".into());
            debug!(room_count = rooms.len(), "ROOM.LIST");
            (format!("OK {}", payload), vec![])
        }
        "ROOM.INFO" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let app = state.read().await;
            match app.room_info(room_id) {
                Ok(info) => {
                    debug!(room_id = room_id, "ROOM.INFO");
                    (format!("OK {}", info), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "ROOM.LABEL" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            let (label, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_label_name(&label) {
                return (e, vec![]);
            }
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let mut app = state.write().await;
            match app.set_room_label(room_id, label.clone()) {
                Ok(()) => {
                    info!(room_id = room_id, label = %label, "ROOM.LABEL");
                    ("OK".into(), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "ROOM.FIND" => {
            let (label, rest) = match take_token(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let app = state.read().await;
            match app.get_room_id_by_label(&label) {
                Ok(id) => {
                    debug!(label = %label, room_id = id, "ROOM.FIND");
                    (format!("OK {}", id), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "SET" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            let (container, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_container_name(&container) {
                return (e, vec![]);
            }
            let (key, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_key_name(&key) {
                return (e, vec![]);
            }
            let value_json = rest.trim_start();
            if value_json.is_empty() {
                return ("ERROR missing_value".into(), vec![]);
            }
            let value: Value = match serde_json::from_str(value_json) {
                Ok(v) => v,
                Err(err) => return (format!("ERROR invalid_json {}", err), vec![]),
            };
            let app = state.write().await;
            match app.set_fragment(room_id, container.clone(), key.clone(), value.clone()) {
                Ok(()) => {
                    let room_counter = app
                        .rooms
                        .get(&room_id)
                        .and_then(|r| r.read().ok().map(|room| room.room_counter))
                        .unwrap_or(0);
                    info!(room_id = room_id, container = %container, key = %key, "SET");
                    (
                        "OK".into(),
                        vec![RoomUpdate {
                            room_id,
                            container,
                            key,
                            value: Some(value),
                            room_counter,
                        }],
                    )
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "DEL" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            let (container, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_container_name(&container) {
                return (e, vec![]);
            }
            let (key, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_key_name(&key) {
                return (e, vec![]);
            }
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let app = state.write().await;
            match app.del_fragment(room_id, container.clone(), key.clone()) {
                Ok(()) => {
                    let room_counter = app
                        .rooms
                        .get(&room_id)
                        .and_then(|r| r.read().ok().map(|room| room.room_counter))
                        .unwrap_or(0);
                    info!(room_id = room_id, container = %container, key = %key, "DEL");
                    (
                        "OK".into(),
                        vec![RoomUpdate {
                            room_id,
                            container,
                            key,
                            value: None,
                            room_counter,
                        }],
                    )
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "GET" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            let (container, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_container_name(&container) {
                return (e, vec![]);
            }
            let (key, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_key_name(&key) {
                return (e, vec![]);
            }
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let app = state.read().await;
            match app.get_fragment(room_id, &container, &key) {
                Ok((v, kv)) => {
                    let value_text = serde_json::to_string(&v).unwrap_or_else(|_| "null".into());
                    debug!(room_id = room_id, container = %container, key = %key, "GET");
                    (format!("OK {} {}", value_text, kv), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "PERSIST.SET" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            let (container, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_container_name(&container) {
                return (e, vec![]);
            }
            let (key, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_key_name(&key) {
                return (e, vec![]);
            }
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let mut app = state.write().await;
            match app.set_fragment_persisted(room_id, container.clone(), key.clone(), true) {
                Ok(()) => {
                    info!(room_id = room_id, container = %container, key = %key, "PERSIST.SET");
                    ("OK".into(), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "PERSIST.UNSET" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            let (container, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_container_name(&container) {
                return (e, vec![]);
            }
            let (key, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_key_name(&key) {
                return (e, vec![]);
            }
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let mut app = state.write().await;
            match app.set_fragment_persisted(room_id, container.clone(), key.clone(), false) {
                Ok(()) => {
                    info!(room_id = room_id, container = %container, key = %key, "PERSIST.UNSET");
                    ("OK".into(), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "PERSIST.GET" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            let (container, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_container_name(&container) {
                return (e, vec![]);
            }
            let (key, rest) = match take_token(rest) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if let Err(e) = validate_key_name(&key) {
                return (e, vec![]);
            }
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let app = state.read().await;
            match app.get_fragment_persisted(room_id, &container, &key) {
                Ok(val) => {
                    debug!(room_id = room_id, container = %container, key = %key, persisted = val, "PERSIST.GET");
                    (format!("OK {}", if val { "true" } else { "false" }), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "VERSION" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let app = state.read().await;
            match app.room_version(room_id) {
                Ok(v) => {
                    debug!(room_id = room_id, version = v, "VERSION");
                    (format!("OK {}", v), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "SET.JWTKEY" => {
            let (key, rest) = match take_token(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let mut app = state.write().await;
            app.set_jwt_key(key);
            info!("SET.JWTKEY called (key hidden)");
            ("OK".into(), vec![])
        }
        "TX.BEGIN" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let app = state.write().await;
            match app.tx_begin(room_id) {
                Ok(()) => {
                    info!(room_id = room_id, "TX.BEGIN");
                    ("OK".into(), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "TX.END" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let app = state.write().await;
            match app.tx_end(room_id) {
                Ok(()) => {
                    let room_counter = app.room_version(room_id).unwrap_or(0);
                    info!(room_id = room_id, "TX.END");
                    (
                        "OK".into(),
                        vec![RoomUpdate {
                            room_id,
                            container: "*".to_string(),
                            key: "*".to_string(),
                            value: None,
                            room_counter,
                        }],
                    )
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "TX.ABORT" => {
            let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            if !rest.trim().is_empty() {
                return ("ERROR extra_arguments".into(), vec![]);
            }
            let app = state.write().await;
            match app.tx_abort(room_id) {
                Ok(()) => {
                    info!(room_id = room_id, "TX.ABORT");
                    ("OK".into(), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "TOKEN.GEN" => {
            let (room_id_str, rest) = match take_token(remainder) {
                Ok(x) => x,
                Err(err) => return (err, vec![]),
            };
            let room_id = match room_id_str.parse::<u64>() {
                Ok(id) => id,
                Err(_) => return ("ERROR invalid_room_id".into(), vec![]),
            };
            let mut containers = Vec::new();
            let mut leftover = rest;
            while !leftover.trim().is_empty() {
                match take_token(leftover) {
                    Ok((tok, rem)) => {
                        containers.push(tok);
                        leftover = rem;
                    }
                    Err(err) => return (err, vec![]),
                }
            }
            let mut app = state.write().await;
            match app.create_room_token(room_id, &containers) {
                Ok(token) => {
                    info!(room_id = room_id, containers = containers.len(), "TOKEN.GEN");
                    (format!("OK {}", token), vec![])
                }
                Err(e) => (error_of(e), vec![]),
            }
        }
        "SAVE" => cmd_save(remainder, state).await,
        "LOAD" => cmd_load(remainder, state).await,
        _ => ("ERROR unknown_command".into(), vec![]),
    }
}

// ─── SAVE / LOAD ─────────────────────────────────────────────────────────────

/// On-disk representation of a single fragment.
#[derive(Serialize, Deserialize)]
struct SavedFragment {
    value: Value,
    key_version: u64,
}

/// On-disk representation of a complete room snapshot.
#[derive(Serialize, Deserialize)]
struct SavedRoom {
    room_counter: u64,
    containers: HashMap<String, HashMap<String, SavedFragment>>,
}

/// `SAVE <room_id> <path>` — atomically snapshot a room to a JSON file.
///
/// Returns when the file has been flushed or on the first error.
/// All other operations against the room return `ERROR room_io_busy` while
/// the save is in progress.
async fn cmd_save(remainder: &str, state: &SharedState) -> (String, Vec<RoomUpdate>) {
    let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
        Ok(x) => x,
        Err(e) => return (e, vec![]),
    };
    let (path, rest) = match take_token(rest) {
        Ok(x) => x,
        Err(e) => return (e, vec![]),
    };
    if !rest.trim().is_empty() {
        return ("ERROR extra_arguments".into(), vec![]);
    }

    // 1. Get the room Arc and set io_locked.
    let room_arc = {
        let app = state.read().await;
        match app.rooms.get(&room_id) {
            Some(arc) => arc.clone(),
            None => return (error_of(StateError::RoomNotFound), vec![]),
        }
    };
    {
        let mut room = match room_arc.write() {
            Ok(g) => g,
            Err(_) => return ("ERROR room_lock_poisoned".into(), vec![]),
        };
        if room.io_locked {
            return ("ERROR room_io_busy".into(), vec![]);
        }
        room.io_locked = true;
    }

    // 2. Serialize room contents (no lock held during file I/O).
    let json_result: Result<String, _> = {
        let room = match room_arc.read() {
            Ok(g) => g,
            Err(_) => {
                room_arc.write().ok().map(|mut r| r.io_locked = false);
                return ("ERROR room_lock_poisoned".into(), vec![]);
            }
        };
        let saved = SavedRoom {
            room_counter: room.room_counter,
            containers: room
                .containers
                .iter()
                .map(|(cname, frags)| {
                    let saved_frags = frags
                        .iter()
                        .map(|(key, entry)| {
                            (
                                key.clone(),
                                SavedFragment {
                                    value: entry.value.clone(),
                                    key_version: entry.key_version,
                                },
                            )
                        })
                        .collect();
                    (cname.clone(), saved_frags)
                })
                .collect(),
        };
        serde_json::to_string_pretty(&saved)
    };

    let json_bytes = match json_result {
        Ok(s) => s,
        Err(e) => {
            room_arc.write().ok().map(|mut r| r.io_locked = false);
            warn!(room_id, %e, "SAVE serialization failed");
            return ("ERROR serialize_failed".into(), vec![]);
        }
    };

    // 3. Write to disk.
    if let Err(e) = tokio::fs::write(&path, json_bytes.as_bytes()).await {
        room_arc.write().ok().map(|mut r| r.io_locked = false);
        warn!(room_id, path = %path, %e, "SAVE file write failed");
        return (format!("ERROR io_failed {}", e), vec![]);
    }

    // 4. Mark all fragments as persisted and unlock.
    {
        let mut room = match room_arc.write() {
            Ok(g) => g,
            Err(_) => return ("ERROR room_lock_poisoned".into(), vec![]),
        };
        for frags in room.containers.values_mut() {
            for entry in frags.values_mut() {
                entry.persisted = true;
            }
        }
        room.io_locked = false;
    }

    info!(room_id, path = %path, "SAVE complete");
    ("OK".into(), vec![])
}

/// `LOAD <room_id> <path>` — replace a room's in-memory state from a JSON file.
///
/// Returns when the load has completed. The command socket stays open until
/// the operation finishes or errors. WS clients receive a wildcard update so
/// they can re-fetch the room state.
///
/// All other operations against the room return `ERROR room_io_busy` while
/// the load is in progress.
async fn cmd_load(remainder: &str, state: &SharedState) -> (String, Vec<RoomUpdate>) {
    let (room_id, rest) = match parse_room_id_from_remainder(remainder) {
        Ok(x) => x,
        Err(e) => return (e, vec![]),
    };
    let (path, rest) = match take_token(rest) {
        Ok(x) => x,
        Err(e) => return (e, vec![]),
    };
    if !rest.trim().is_empty() {
        return ("ERROR extra_arguments".into(), vec![]);
    }

    // 1. Get the room Arc and set io_locked.
    let room_arc = {
        let app = state.read().await;
        match app.rooms.get(&room_id) {
            Some(arc) => arc.clone(),
            None => return (error_of(StateError::RoomNotFound), vec![]),
        }
    };
    {
        let mut room = match room_arc.write() {
            Ok(g) => g,
            Err(_) => return ("ERROR room_lock_poisoned".into(), vec![]),
        };
        if room.io_locked {
            return ("ERROR room_io_busy".into(), vec![]);
        }
        room.io_locked = true;
    }

    // 2. Read file from disk (no room lock held).
    let file_bytes = match tokio::fs::read(&path).await {
        Ok(b) => b,
        Err(e) => {
            room_arc.write().ok().map(|mut r| r.io_locked = false);
            warn!(room_id, path = %path, %e, "LOAD file read failed");
            return (format!("ERROR io_failed {}", e), vec![]);
        }
    };

    // 3. Deserialize.
    let saved: SavedRoom = match serde_json::from_slice(&file_bytes) {
        Ok(s) => s,
        Err(e) => {
            room_arc.write().ok().map(|mut r| r.io_locked = false);
            warn!(room_id, path = %path, %e, "LOAD deserialize failed");
            return (format!("ERROR invalid_json {}", e), vec![]);
        }
    };

    // 4. Replace room state and unlock.
    let new_counter = saved.room_counter;
    {
        let mut room = match room_arc.write() {
            Ok(g) => g,
            Err(_) => return ("ERROR room_lock_poisoned".into(), vec![]),
        };
        room.containers.clear();
        room.tx_buffer = None;
        room.room_counter = new_counter;
        for (cname, frags) in saved.containers {
            let container = room.containers.entry(cname).or_default();
            for (key, frag) in frags {
                container.insert(
                    key,
                    crate::state::FragmentEntry {
                        value: frag.value,
                        key_version: frag.key_version,
                        persisted: true,
                    },
                );
            }
        }
        room.io_locked = false;
    }

    info!(room_id, path = %path, room_counter = new_counter, "LOAD complete");
    (
        "OK".into(),
        vec![RoomUpdate {
            room_id,
            container: "*".to_string(),
            key: "*".to_string(),
            value: None,
            room_counter: new_counter,
        }],
    )
}

fn take_token(input: &str) -> Result<(String, &str), String> {
    let input = input.trim_start();
    if input.is_empty() {
        return Err("ERROR missing_argument".into());
    }

    if input.starts_with('"') {
        let mut buf = String::new();
        let mut escaped = false;
        for (i, c) in input[1..].char_indices() {
            if escaped {
                match c {
                    '\\' => buf.push('\\'),
                    '"' => buf.push('"'),
                    'n' => buf.push('\n'),
                    'r' => buf.push('\r'),
                    't' => buf.push('\t'),
                    other => buf.push(other),
                }
                escaped = false;
                continue;
            }

            if c == '\\' {
                escaped = true;
                continue;
            }

            if c == '"' {
                let end = 1 + i + c.len_utf8();
                let rest = &input[end..];
                return Ok((buf, rest));
            }

            buf.push(c);
        }

        Err("ERROR invalid_argument".into())
    } else {
        let mut end = input.len();
        for (i, c) in input.char_indices() {
            if c.is_whitespace() {
                end = i;
                break;
            }
        }
        let token = input[..end].to_string();
        let rest = &input[end..];
        Ok((token, rest))
    }
}

fn parse_room_id_from_remainder(remainder: &str) -> Result<(u64, &str), String> {
    let (room_id, rest) = take_token(remainder)?;
    let parsed = room_id
        .parse::<u64>()
        .map_err(|_| "ERROR invalid_room_id".to_string())?;
    Ok((parsed, rest))
}

fn error_of(err: StateError) -> String {
    warn!(error = %err, "state error");
    format!("ERROR {}", err)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::{AppState, SharedState};
    use std::sync::Arc;
    use tokio::sync::RwLock;

    fn sample_state() -> SharedState {
        let mut app = AppState::new();
        app.set_command_api_key("secret".to_string()).unwrap();
        Arc::new(RwLock::new(app))
    }

    #[tokio::test]
    async fn test_process_command_flow() {
        let state = sample_state();

        let (resp, _) = process_command("ROOM.CREATE", &state).await;
        assert!(resp.starts_with("OK"));

        let (resp, updates) = process_command("SET 1 public foo \"bar\"", &state).await;
        assert_eq!(resp, "OK");
        assert_eq!(updates.len(), 1);

        let (resp, _) = process_command("GET 1 public foo", &state).await;
        assert!(resp.starts_with("OK \"bar\""));

        let (resp, _) = process_command("VERSION 1", &state).await;
        assert_eq!(resp, "OK 1");

        let (resp, updates) = process_command("DEL 1 public foo", &state).await;
        assert_eq!(resp, "OK");
        assert_eq!(updates.len(), 1);

        let (resp, _) = process_command("GET 1 public foo", &state).await;
        assert_eq!(resp, "ERROR tombstone");
    }

    #[tokio::test]
    async fn test_process_command_quoted_and_json_spaces() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        let (resp, updates) = process_command(
            "SET 1 \"my container\" \"complex key\" {\"a\": \"hello world\", \"b\": 123}",
            &state,
        )
        .await;
        assert_eq!(resp, "OK");
        assert_eq!(updates.len(), 1);

        let (resp, _) =
            process_command("GET 1 \"my container\" \"complex key\"", &state).await;
        assert!(resp.starts_with("OK {\"a\":\"hello world\",\"b\":123}"));
    }

    #[tokio::test]
    async fn test_process_command_malformed_command() {
        let state = sample_state();

        let (resp, _) = process_command("ROOM.CREATE extra", &state).await;
        assert_eq!(resp, "ERROR extra_arguments");

        let (resp, _) = process_command("SET 1 public key", &state).await;
        assert_eq!(resp, "ERROR missing_value");

        let (resp, _) = process_command("SET 1 public key invalid_json", &state).await;
        assert!(resp.starts_with("ERROR invalid_json"));
    }

    #[tokio::test]
    async fn test_process_command_room_info_invalid_room_id() {
        let state = sample_state();

        let (resp, _) = process_command("ROOM.INFO foo", &state).await;
        assert_eq!(resp, "ERROR invalid_room_id");
    }

    #[tokio::test]
    async fn test_process_command_set_invalid_json() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        let (resp, _) =
            process_command("SET 1 public foo {not-a-json}", &state).await;
        assert!(resp.starts_with("ERROR invalid_json"));
    }

    #[tokio::test]
    async fn test_process_tx_sequence() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        let (resp, _) = process_command("TX.BEGIN 1", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) = process_command("SET 1 public x 10", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) = process_command("TX.END 1", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) = process_command("GET 1 public x", &state).await;
        assert!(resp.starts_with("OK 10"));
    }

    #[tokio::test]
    async fn test_tx_end_with_del_tombstones_missing_key() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        let (resp, _) = process_command("TX.BEGIN 1", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) =
            process_command("DEL 1 public missing-key", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) = process_command("TX.END 1", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) =
            process_command("GET 1 public missing-key", &state).await;
        assert_eq!(resp, "ERROR tombstone");
    }

    #[tokio::test]
    async fn test_tx_conflict_and_ordering_edge_cases() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        // Cannot begin second transaction while first is open.
        let (resp, _) = process_command("TX.BEGIN 1", &state).await;
        assert_eq!(resp, "OK");
        let (resp, _) = process_command("TX.BEGIN 1", &state).await;
        assert_eq!(resp, "ERROR tx_already_open");

        // Interleaved transactional operations are committed in order.
        let (resp, _) = process_command("SET 1 public a 1", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) = process_command("DEL 1 public a", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) = process_command("SET 1 public a 2", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) = process_command("TX.END 1", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) = process_command("GET 1 public a", &state).await;
        assert!(resp.starts_with("OK 2"));
    }

    #[tokio::test]
    async fn test_token_gen_requires_jwt_key() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        let (resp, _) = process_command("TOKEN.GEN 1 public", &state).await;
        assert_eq!(resp, "ERROR jwt_key_not_configured");
    }

    #[tokio::test]
    async fn test_set_container_key_length_limits() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        let long_container = "a".repeat(MAX_COMMAND_CONTAINER_LEN + 1);
        let cmd = format!("SET 1 {} key 10", long_container);
        let (resp, _) = process_command(&cmd, &state).await;
        assert_eq!(resp, "ERROR container_name_too_long");

        let long_key = "k".repeat(MAX_COMMAND_KEY_LEN + 1);
        let cmd = format!("SET 1 public {} 10", long_key);
        let (resp, _) = process_command(&cmd, &state).await;
        assert_eq!(resp, "ERROR key_too_long");
    }

    #[test]
    fn test_command_api_key_invalid() {
        let mut app = AppState::new();
        let result = app.set_command_api_key("".to_string());
        assert!(matches!(result, Err(StateError::CommandApiKeyInvalid)));
    }

    #[tokio::test]
    async fn test_room_list_and_delete() {
        let state = sample_state();

        // Empty list
        let (resp, _) = process_command("ROOM.LIST", &state).await;
        assert_eq!(resp, "OK []");

        // Create two rooms
        process_command("ROOM.CREATE", &state).await;
        process_command("ROOM.CREATE", &state).await;

        let (resp, _) = process_command("ROOM.LIST", &state).await;
        assert!(resp.starts_with("OK "));
        let ids: Vec<u64> = serde_json::from_str(&resp[3..]).unwrap();
        assert_eq!(ids, vec![1u64, 2u64]);

        // Delete room 1
        let (resp, _) = process_command("ROOM.DELETE 1", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) = process_command("ROOM.LIST", &state).await;
        let ids: Vec<u64> = serde_json::from_str(&resp[3..]).unwrap();
        assert_eq!(ids, vec![2u64]);

        // Delete non-existent room
        let (resp, _) = process_command("ROOM.DELETE 999", &state).await;
        assert_eq!(resp, "ERROR room_not_found");

        // ROOM.DELETE with no room ID
        let (resp, _) = process_command("ROOM.DELETE", &state).await;
        assert_eq!(resp, "ERROR missing_argument");

        // ROOM.LIST extra args
        let (resp, _) = process_command("ROOM.LIST extra", &state).await;
        assert_eq!(resp, "ERROR extra_arguments");
    }

    #[tokio::test]
    async fn test_room_info_command() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;
        process_command("SET 1 public k 42", &state).await;

        let (resp, _) = process_command("ROOM.INFO 1", &state).await;
        assert!(resp.starts_with("OK "));
        let info: serde_json::Value = serde_json::from_str(&resp[3..]).unwrap();
        assert_eq!(info["room_id"], serde_json::json!(1u64));
        assert_eq!(info["room_counter"], serde_json::json!(1u64));
        assert_eq!(info["fragment_count"], serde_json::json!(1usize));

        // Non-existent room
        let (resp, _) = process_command("ROOM.INFO 999", &state).await;
        assert_eq!(resp, "ERROR room_not_found");

        // Extra args
        let (resp, _) = process_command("ROOM.INFO 1 extra", &state).await;
        assert_eq!(resp, "ERROR extra_arguments");
    }

    #[tokio::test]
    async fn test_version_command() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        let (resp, _) = process_command("VERSION 1", &state).await;
        assert_eq!(resp, "OK 0");

        process_command("SET 1 public x 1", &state).await;

        let (resp, _) = process_command("VERSION 1", &state).await;
        assert_eq!(resp, "OK 1");

        // Non-existent room
        let (resp, _) = process_command("VERSION 999", &state).await;
        assert_eq!(resp, "ERROR room_not_found");

        // Extra args
        let (resp, _) = process_command("VERSION 1 extra", &state).await;
        assert_eq!(resp, "ERROR extra_arguments");
    }

    #[tokio::test]
    async fn test_tx_abort_command() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        process_command("TX.BEGIN 1", &state).await;
        process_command("SET 1 public k 99", &state).await;

        let (resp, _) = process_command("TX.ABORT 1", &state).await;
        assert_eq!(resp, "OK");

        // k should not be set
        let (resp, _) = process_command("GET 1 public k", &state).await;
        assert_eq!(resp, "ERROR container_not_found");

        // Extra args
        let (resp, _) = process_command("TX.ABORT 1 extra", &state).await;
        assert_eq!(resp, "ERROR extra_arguments");
    }

    #[tokio::test]
    async fn test_set_jwtkey_command() {
        let state = sample_state();

        let (resp, _) = process_command("SET.JWTKEY mysecretkey", &state).await;
        assert_eq!(resp, "OK");

        // Extra args after key
        let (resp, _) = process_command("SET.JWTKEY k1 k2", &state).await;
        assert_eq!(resp, "ERROR extra_arguments");

        // Missing key
        let (resp, _) = process_command("SET.JWTKEY", &state).await;
        assert_eq!(resp, "ERROR missing_argument");
    }

    #[tokio::test]
    async fn test_token_gen_success() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        // Setup JWT key via command
        process_command(
            "SET.JWTKEY a_long_enough_secret_key_32bytes_+",
            &state,
        )
        .await;
        {
            let mut app = state.write().await;
            app.set_jwt_issuer("syncpond".to_string());
            app.set_jwt_audience("client".to_string());
        }

        let (resp, _) = process_command("TOKEN.GEN 1 public priv", &state).await;
        assert!(resp.starts_with("OK "), "expected OK got: {}", resp);
        let token = &resp[3..];
        let parts: Vec<&str> = token.split('.').collect();
        assert_eq!(parts.len(), 3, "token must be a valid JWT");
    }

    #[tokio::test]
    async fn test_token_gen_invalid_room_id_non_numeric() {
        let state = sample_state();

        let (resp, _) = process_command("TOKEN.GEN notanumber", &state).await;
        assert_eq!(resp, "ERROR invalid_room_id");
    }

    #[tokio::test]
    async fn test_get_missing_room_and_key() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        // Missing room
        let (resp, _) = process_command("GET 999 public foo", &state).await;
        assert_eq!(resp, "ERROR room_not_found");

        // Missing container
        let (resp, _) = process_command("GET 1 no_container foo", &state).await;
        assert_eq!(resp, "ERROR container_not_found");

        // Missing key
        process_command("SET 1 public existing 1", &state).await;
        let (resp, _) = process_command("GET 1 public no_key", &state).await;
        assert_eq!(resp, "ERROR not_found");
    }

    #[tokio::test]
    async fn test_del_missing_room() {
        let state = sample_state();

        let (resp, _) = process_command("DEL 999 public foo", &state).await;
        assert_eq!(resp, "ERROR room_not_found");
    }

    #[tokio::test]
    async fn test_unknown_command() {
        let state = sample_state();

        let (resp, _) = process_command("NONEXISTENT.COMMAND arg1", &state).await;
        assert_eq!(resp, "ERROR unknown_command");
    }

    #[tokio::test]
    async fn test_empty_command_line() {
        let state = sample_state();

        // Completely empty
        let (resp, _) = process_command("", &state).await;
        assert_eq!(resp, "ERROR missing_argument");
    }

    #[tokio::test]
    async fn test_set_on_nonexistent_room() {
        let state = sample_state();

        let (resp, _) = process_command("SET 999 public foo 1", &state).await;
        assert_eq!(resp, "ERROR room_not_found");
    }

    #[tokio::test]
    async fn test_room_delete_extra_args() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        let (resp, _) = process_command("ROOM.DELETE 1 extra", &state).await;
        assert_eq!(resp, "ERROR extra_arguments");
    }

    #[tokio::test]
    async fn test_room_label_and_find() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;

        let (resp, _) = process_command("ROOM.LABEL 1 mylabel", &state).await;
        assert_eq!(resp, "OK");

        let (resp, _) = process_command("ROOM.FIND mylabel", &state).await;
        assert_eq!(resp, "OK 1");

        // quoted label with spaces
        let (resp, _) =
            process_command("ROOM.LABEL 1 \"My Room\"", &state).await;
        assert_eq!(resp, "OK");
        let (resp, _) = process_command("ROOM.FIND \"My Room\"", &state).await;
        assert_eq!(resp, "OK 1");
    }

    #[tokio::test]
    async fn test_room_label_in_use_and_missing() {
        let state = sample_state();
        process_command("ROOM.CREATE", &state).await;
        process_command("ROOM.CREATE", &state).await; // room 2

        let (resp, _) = process_command("ROOM.LABEL 1 shared", &state).await;
        assert_eq!(resp, "OK");

        // Attempt to label room 2 with same label -> error
        let (resp, _) = process_command("ROOM.LABEL 2 shared", &state).await;
        assert_eq!(resp, "ERROR label_in_use");

        // Finding a non-existent label
        let (resp, _) =
            process_command("ROOM.FIND no_such_label", &state).await;
        assert_eq!(resp, "ERROR label_not_found");
    }
}
